---
title: "Newtwork Analysis - Eels Group"
author: "Created by: Walid Hedidar"
date: "Date: 5/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<h2> Welcome! </h2>


This website summarizes a network analysis conducted on data from the BDS516 class. This tab includes details about the methodology/dataset. The Analysis tab will include details about the analysis and findings. Finally, the About tab will contain details about the contributors to the project. 

<h3> Methodology/Dataset </h3>


Our network analysis used data collected from a survey administered in BDS516 class. This survey sought to understand the different connections between different members of the class and the types of these connections, using the following scale: 

1. I have texted in the last 7 days

2. I have met during my time in MBDS

3. Is my friend

4. I ask for advice/help

5. Asks me for help/advice


The survey also included a self-reporting of personality type using the following scale:

1. Introverted
2. Middle ground
3. Extroverted

